# Generated by Django 5.2.1 on 2025-05-22 19:23

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [VectorExtension()]
